//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyerAccountingV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionId { get; set; }
        public int PageId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageId { get; set; }
        public bool IsActive { get; set; }
        public string Content { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual StockImage StockImage { get; set; }
    }
}
