//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyerAccountingV2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int TestimonialId { get; set; }
        public string Author { get; set; }
        public string AuthorTitle { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public string Comment { get; set; }
        public bool IsActive { get; set; }
    }
}
